# Generated by Django 5.2.12 on 2026-03-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetotp_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
