# Generated by Django 5.2.13 on 2026-04-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='qr_data',
        ),
    ]
